CREATE TYPE EXPORT_DECLARATION_STATUS AS ENUM ('PENDING', 'DONE', 'ERROR');

CREATE TYPE EXPORT_DECLARATION_DESTINATION AS ENUM ('JSON', 'DATABASE');

CREATE TABLE export_declaration (
    id                  BIGINT                                    NOT NULL,
    created_date        TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
    version             BIGINT                      DEFAULT 0     NOT NULL,

    date                TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    exporter_account_id BIGINT                                    NOT NULL,
    status              EXPORT_DECLARATION_STATUS                 NOT NULL,
    description         CHARACTER VARYING(255)                    NOT NULL,
    error_details       JSONB,
    destination         EXPORT_DECLARATION_DESTINATION            NOT NULL,
    source_database_id  BIGINT                                    NOT NULL,
    target_database_id  BIGINT
);

ALTER TABLE export_declaration
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME export_declaration_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


ALTER TABLE export_declaration
    ADD CONSTRAINT export_declaration_pkey PRIMARY KEY (id);


ALTER TABLE export_declaration
    ADD CONSTRAINT fk_exporter_account_id FOREIGN KEY (exporter_account_id) REFERENCES account(id) NOT VALID;

ALTER TABLE export_declaration
    VALIDATE CONSTRAINT fk_exporter_account_id;


ALTER TABLE export_declaration
    ADD CONSTRAINT fk_source_database_id FOREIGN KEY (source_database_id) REFERENCES database(id) NOT VALID;

ALTER TABLE export_declaration
    VALIDATE CONSTRAINT fk_source_database_id;


ALTER TABLE export_declaration
    ADD CONSTRAINT fk_target_database_id FOREIGN KEY (target_database_id) REFERENCES database(id) NOT VALID;

ALTER TABLE export_declaration
    VALIDATE CONSTRAINT fk_target_database_id;
