CREATE TYPE authority AS ENUM (
    'ROLE_USER',
    'ROLE_MODERATOR',
    'ROLE_ADMIN'
    );


CREATE TYPE gender AS ENUM (
    'MALE',
    'FEMALE'
    );


CREATE TABLE account (
    id                 bigint                                                NOT NULL,
    created_date       timestamp without time zone DEFAULT now()             NOT NULL,
    last_modified_date timestamp without time zone DEFAULT now()             NOT NULL,
    version            bigint                      DEFAULT 0                 NOT NULL,

    username           character varying(255),
    email              character varying(255),
    password           character varying(255),
    enabled            boolean                     DEFAULT true              NOT NULL,
    gender             gender,
    roles              authority[]                 DEFAULT '{}'::authority[] NOT NULL,
    registration_date  timestamp without time zone DEFAULT now()             NOT NULL
);


ALTER TABLE account
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME account_id_seq
        START
            WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


SELECT pg_catalog.setval('account_id_seq', 1, true);


ALTER TABLE ONLY account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


ALTER TABLE ONLY account
    ADD CONSTRAINT uk_account_username UNIQUE (username);


CREATE TRIGGER increase_version
    BEFORE UPDATE
    ON account
    FOR EACH ROW
EXECUTE FUNCTION increase_version();

CREATE TRIGGER update_last_modified_date
    BEFORE UPDATE
    ON account
    FOR EACH ROW
EXECUTE FUNCTION update_last_modified_date();
