CREATE TABLE topic (
    id                 bigint                                    NOT NULL,
    created_date       timestamp without time zone DEFAULT now() NOT NULL,
    last_modified_date timestamp without time zone DEFAULT now() NOT NULL,
    version            bigint                      DEFAULT 0     NOT NULL,

    title              text                                      NOT NULL,
    content            text                                      NOT NULL,
    post_count         integer                     DEFAULT 0     NOT NULL,
    slug               text                                      NOT NULL,
    author_id          bigint                                    NOT NULL,
    category_id        bigint                                    NOT NULL,
    last_post_id       bigint,
    post_date          timestamp without time zone DEFAULT now() NOT NULL,
    last_post_date     timestamp without time zone DEFAULT now() NOT NULL,
    visible            boolean                     DEFAULT true  NOT NULL,
    pinned             boolean                     DEFAULT false NOT NULL
);


ALTER TABLE topic
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME topic_id_seq
        START
            WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


SELECT pg_catalog.setval('topic_id_seq', 1, true);


ALTER TABLE ONLY topic
    ADD CONSTRAINT topic_pkey PRIMARY KEY (id);


ALTER TABLE ONLY topic
    ADD CONSTRAINT uk_topic_slug UNIQUE (slug);


CREATE TRIGGER increase_version
    BEFORE UPDATE
    ON topic
    FOR EACH ROW
EXECUTE FUNCTION increase_version();

CREATE TRIGGER update_last_modified_date
    BEFORE UPDATE
    ON topic
    FOR EACH ROW
EXECUTE FUNCTION update_last_modified_date();
