/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.zhokhov.dumper.app;

import com.zhokhov.dumper.list.LinkedList;

import static com.zhokhov.dumper.utilities.StringUtils.join;
import static com.zhokhov.dumper.utilities.StringUtils.split;
import static com.zhokhov.dumper.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
